### ISSUE TITLE
How might convert case handle embedded abbreviations?

### ISSUE THREAD

**Issue by sjordan1975** [zellwk/javascript#13]
Thank you for a very cool utility with convert case.

The one fairly common string I've not gotten good results is for strings containing abbreviations; things like: employeeID

A common expected output would be 
```
toTitle('employeeID') => Employee ID
```

At the moment, I get 
```
toTitle('employeeID') => Employee I D
```

**Comment by zellwk** [comment]
It sounds like what you'll need to do here is split out the abbreviated parts because there's no way to tell what's an abbreviation and what's not. 

Example: 

```
toTitle('Employee') + ' ID'
```

**Comment by sjordan1975** [comment]
@zellwk Thank you

Yeah, I was thinking I might have to do something like that -- create a dictionary of abbreviations.

I actually found your library after trying a bunch of regex listed on Stackover -- a user asked that example questions: "How to make employeeID => Employee ID"

Here's the link if you're curious:
https://stackoverflow.com/questions/18379254/regex-to-split-camel-case

Cheers

**Comment by zellwk** [comment]
Thanks for letting me know. Hope you have a good answer now :)

**Comment by sjordan1975** [comment]
@zellwk 

A working example

```
import { toTitle } from "./convert-case.js";

// NB. Assume sequential single chars can be concatenated
// ex. N B A Finals => NBA Finals
const reducer = (total, currentValue, currentIndex, arr) => {
  if (
    currentValue.length === 1 &&
    !(currentIndex > 0 && arr[currentIndex - 1].length > 1)
  ) {
    return total + currentValue;
  } else {
    return total + " " + currentValue;
  }
};

const concatSingleChars = (title) => {
  const arrTitle = title.split(" ");
  return arrTitle.reduce(reducer);
};

const convertCase = (str) => {
  const s = toTitle(str);
  return concatSingleChars(s);
};

const tests = [
  "colName",
  "This_Is_A_title",
  "And_How_About_thisOne",
  "MaryHadALittleLamb",
  "employeeID",
  "N B A Finals",
  "N B A Finals in L A",
  "I Love L A"
];

const titles = tests.map((test) => {
  return convertCase(test);
});

console.log(titles);
```
