### ISSUE TITLE
List of Focusable Elements

### ISSUE THREAD

**Issue by aesyondu** [zellwk/javascript#2]
https://github.com/zellwk/useful-js-snippets/blob/ce4d6cc6bf50e98d91124ee0e276938ef78c624e/script/elements.js#L46

Hi, just read the article https://zellwk.com/blog/keyboard-focusable-elements/, featured on Frontend Focus. It reminded me of this list of focusable elements:

https://github.com/jkup/focusable/blob/5769a9cd52d6b20be03642c825d3977cb2fcc34e/index.js#L1

```javascript
module.exports = 'a[href], area[href], input:not([disabled]):not([type="hidden"]), select:not([disabled]), textarea:not([disabled]), button:not([disabled]), iframe, object, embed, [tabindex="0"], [contenteditable], audio[controls], video[controls], summary, [tabindex^="0"], [tabindex^="1"], [tabindex^="2"], [tabindex^="3"], [tabindex^="4"], [tabindex^="5"], [tabindex^="6"], [tabindex^="7"], [tabindex^="8"], [tabindex^="9"]'
```

**Comment by zellwk** [comment]
Interesting list. I know of most of them at this point, but don't have the space to do further testing yet.

**Comment by zellwk** [comment]
Closing for now since I'm not interested in further testing at this point.

**Comment by zellwk** [comment]
@aesyondu  I know this may be a long time since you mentioned the PR — and I don't know when I included your input into my list... but as of [v3.2.4](https://github.com/zellwk/javascript/releases/tag/v3.2.4) we have included everything you mentioned 🙂
