### ISSUE TITLE
focusable selector list incomplete

### ISSUE THREAD

**Issue by waffledonkey** [zellwk/javascript#7]
https://github.com/zellwk/javascript/blob/56ecd4a74000343229198ee27ac762d1ef52c818/browser/focusable/focusable.js#L9

You're missing dialog, [contenteditable], audio, video, iframe and I want to say others...

tabindex may be over-broad.  I see you have keyboardOnly, so maybe the nuances of tabindex are covered and it's OK.

**Comment by zellwk** [comment]
Not bothering with these for now. Please add PR if you want to add them it. Thanks.

**Comment by zellwk** [comment]
@waffledonkey I know this may be a long time since you mentioned the PR — and I don't know when I included your input into my list... but as of [v3.2.4](https://github.com/zellwk/javascript/releases/tag/v3.2.4) we have included everything you mentioned 🙂
