### ISSUE TITLE
call Date.now() statically?

### ISSUE THREAD

**Issue by waffledonkey** [zellwk/javascript#9]
https://github.com/zellwk/javascript/blob/56ecd4a74000343229198ee27ac762d1ef52c818/browser/store/store.js#L50
```
const now = new Date()
...
now.getTime() + _whatever_
```
obviously works, but you could just use `Date.now()` and not need to declare a constant you're not really doing anything with.

**Comment by zellwk** [comment]
Sure, makes sense.
